# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py310, py311, py312, py313

[testenv]
extras = dev
commands =
    pytest -s -W ignore::DeprecationWarning

[flake8]
max-line-length = 120
extend-exclude = .venv*,venv*,build,dist,docs/_build,*.egg-info
